"""auto update

Revision ID: a349bc2003f4
Revises: 115690b64e9c
Create Date: 2026-03-12 16:03:11.665665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a349bc2003f4'
down_revision: Union[str, Sequence[str], None] = '115690b64e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('rule_value', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_rules_id'), 'brand_rules', ['id'], unique=False)
    op.create_table('brand_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('background_color', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.Column('font_family', sa.String(), nullable=True),
    sa.Column('button_style', sa.String(), nullable=True),
    sa.Column('border_radius', sa.String(), nullable=True),
    sa.Column('display_mode', sa.String(), nullable=True),
    sa.Column('tone_of_voice', sa.String(), nullable=True),
    sa.Column('aesthetic_description', sa.String(), nullable=True),
    sa.Column('module_name_closet', sa.String(), nullable=True),
    sa.Column('module_name_looks', sa.String(), nullable=True),
    sa.Column('module_name_recommendations', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_settings_id'), 'brand_settings', ['id'], unique=False)
    op.create_table('curated_look_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('look_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_look_items_id'), 'curated_look_items', ['id'], unique=False)
    op.create_table('curated_looks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ocasiao', sa.String(), nullable=True),
    sa.Column('estilo', sa.String(), nullable=True),
    sa.Column('descricao_editorial', sa.String(), nullable=True),
    sa.Column('observacoes_marca', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_looks_id'), 'curated_looks', ['id'], unique=False)
    op.create_table('recommendation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('look_id', sa.Integer(), nullable=True),
    sa.Column('produtos_recomendados', sa.String(), nullable=True),
    sa.Column('ocasiao', sa.String(), nullable=True),
    sa.Column('fonte', sa.String(), nullable=True),
    sa.Column('clicado', sa.Boolean(), nullable=True),
    sa.Column('aprovado_marca', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_logs_id'), 'recommendation_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_logs_id'), table_name='recommendation_logs')
    op.drop_table('recommendation_logs')
    op.drop_index(op.f('ix_curated_looks_id'), table_name='curated_looks')
    op.drop_table('curated_looks')
    op.drop_index(op.f('ix_curated_look_items_id'), table_name='curated_look_items')
    op.drop_table('curated_look_items')
    op.drop_index(op.f('ix_brand_settings_id'), table_name='brand_settings')
    op.drop_table('brand_settings')
    op.drop_index(op.f('ix_brand_rules_id'), table_name='brand_rules')
    op.drop_table('brand_rules')
    # ### end Alembic commands ###